version: "3.3"

services:
  web:
    container_name: afterlogic-webmail-lite
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
  db:
    image: mysql:8
    command: --mysql-native-password=ON
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_Pwd
      MYSQL_DATABASE: afterlogic
      MYSQL_USER: afterlogic
      MYSQL_PASSWORD: docker_Bundle
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
